remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
tittle: Розробка 2D-гри "Grimcaster"
description: Дипломна робота Дерев'янка О.Р.
# Розробка 2d гри "Grimcaster"
«Кваліфікаційна робота на підтвердження ступеня фахового молодшого бакалавра (ВСП «ППФК НТУ «ХПІ»).
## Завдання до дипломної роботи
Розроблений програмний продукт має являти собою 2D-гру у жанрі CCG(Collectible Card Game). Основна мате гравця - зібрати колоду потужних карт, побороти всіх ворогів, отримати винагороди. Розробку виконати мовою GDScript, C# з використанням рушія GoDot. Слід подбати про зручне меню та наявність гарно ілюстрованих карт, можлиість анімації бою. Готовий продукт опублікувати в одному з онлайнових ігрових магазинів (itch.io тощо).
